"""empty message

Revision ID: 00e9dbada757
Revises: 
Create Date: 2021-02-06 04:58:50.714688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e9dbada757'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('classId', sa.Integer(), nullable=False),
    sa.Column('className', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('classId')
    )
    op.create_table('lecture',
    sa.Column('lectureId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('className', sa.String(length=30), nullable=True),
    sa.Column('lecturer', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('lectureId')
    )
    op.create_table('quiz',
    sa.Column('quizId', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=50), nullable=True),
    sa.Column('answer', sa.String(length=50), nullable=True),
    sa.Column('response', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('quizId')
    )
    op.create_table('student',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('tutor',
    sa.Column('tutorId', sa.Integer(), nullable=False),
    sa.Column('tutorName', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('tutorId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutor')
    op.drop_table('student')
    op.drop_table('quiz')
    op.drop_table('lecture')
    op.drop_table('classes')
    # ### end Alembic commands ###
